apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: Secret
metadata:
  name: default-server-secret
  namespace: nginx-ingress
type: Opaque
data:
  tls.crt:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvekNDQXVlZ0F3SUJBZ0lKQU9TM2JmT2FoMVNXTUEwR0NTcUdTSWIzRFFFQkN3VUFNQll4RkRBU0JnTlYKQkFNTUMyVjRZVzF3YkdVdVkyOXRNQjRYRFRFNU1ERXhOVEV5TlRBMU1sb1hEVEl3TURFeE5URXlOVEExTWxvdwpGakVVTUJJR0ExVUVBd3dMWlhoaGJYQnNaUzVqYjIwd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFEakZkNWEyNk9oVmtTTkZ2OTF4aVVVclljT2kxMjdOc0pJYnFKM09Cci9HZDlRTFRERUFCL04KQXgwaDFyellyVGt3LzlJdzZvT2VrVTQybkZidXJtczhoZHFhTTNwWnRmMzVzdFlnL1IxUVdUYlc3N2Y3SzlGdAprNnFOV0dYTHc1Ti9KY3M4TXFrc2FjUzByUXUyLzFXZ0hhR3lJMW84YTk1SjZiZkJLTXpPb0Z2VUdESlFuaTN4CkJpQUtUKzRFdVRqd3JZditITWtrUmRZZ2hCcGVwZnc0TVVzcjRQV3lpbU5OUTM4TzlML0krcCt1Y0RkRS82WWgKZ29UdG1lVEQzbEVGN0R4R0FUTDIwR2phNmdTMTQyMFBPNjErSS82YlpEMi9oaGU1anFwWU5XRVMyZXFnYkRoNQpWYUtVRGl2WjhXMWJRV2hWTW5JWkVtZ1NHTllYKy9UU3FrNjFVTlk1WEx4ZjIvVFlQZlhUU1dWYXVxclpMbE5iCjdzOTRLZGd4QzJMSTNweEIrcndyaHYrdE1OK3ZxOTBGYkVYOEhMYmdqbHNJUGpVVFEvck9oZitud2JBV05JMmgKUW9EbGJLOEUyS1lBc3B3bmhabjh2QjVVbXo2a3VVYU9Wa3ZTcmcrNUkybGpGZTVxMDEwdldwSlJmNjA2RkVqVQpWakswYlVnNThBclJKV2gyY2hBanFVTTdUem9SMVNGSUkvamhvSytreGl3b0RNS1BrQ2hlUmQrM2Y5WmhPY3JPCm5mSmZaVlV6ZWlhaTF3TE9XUjFWMVNCSnMzYXRaS0dPSUZWY3M3ekIyVXAwVW50UmJ0T1NJRkQvRWNqS1E3OFMKdkd1Q1Frb1k0SXUzb0dIdUFNZFQxTWxyT2NsLzhLSENXNWV4V2V0QytMM08vbllKejRsVWV3SURBUUFCbzFBdwpUakFkQmdOVkhRNEVGZ1FVWDUvdXd0bWdTOTU5akVRbWdwVklTRmFLV3Ywd0h3WURWUjBqQkJnd0ZvQVVYNS91Cnd0bWdTOTU5akVRbWdwVklTRmFLV3Ywd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQWdFQU9VcUp2YWNxbVBtM1RpK294U0pHRXNUZXRWTFpmNHNETi9ZSFhjc1FuVXRGVlAzc1p3NkxsY1hUYy9TLwpEc281MnFWdnBETlF4VXNhVXZtMVVReVdNVnhDSWczMGFpeDMwbkIzMmcrUW8vYVZ1TitqR2k0R1k0cURFcFJWCjU4QnBnRG5ZNjBwN2lPaEx4WEpMTHR0ZldrYXgvcUlJQVR1ZGp1WWFLYWZ3T3E4YlVDNWRxVStmVm5EMFhRaEYKQ1poUFBzZDREME0zYXFBOTdzN2NTOGh1TDZQdVZ5SmNEb1A5VE42LzVDNWYzS0cyeWgxZVhISVdXdG5Hb3U0UwpKMFl5QnVJWXFPcHV6eWRXeGhQVUY3ZmxUWlgrVlliU21EbnJyUWw1MnF6L0o2ZW1pNXpKc3NkRVVlSGt4SXI4Ck05WmkxREI5ODBtamVJSk9iRmUrVFJOaDU5TDhKTnR5TVJlbGRETEVBaHpCc3Uya0pFUlRZVG9QU0p1MkJFQ28KNzZVZUlJSUQrUktVKzZZbXMrdlhHSmlCTG9kWjdHTnU3QlYzK1Fra0RCUy9jZHJhdE5WRzlLTFZ5eXZoRS9BYgpXSTdHUVh4bjBnTE53YW5xNWpmemNXNlArcHN3K2FwNGxkd0U4UjFrYWY5SXhSVUM3NEQ2T2VCQ0pEeXhsWVJkCjFsT1BrYWU4ek5teTl3SU9mZXBxNVo3T2dnZGZJdEdpRkZLZXcxOHUyejdlOVJoVmxjdE8wb0tLZzAzWUFQeUgKdXgyUVlScFFlMlJXOGxnOHhhV2x2K1ZzRDQ0R3NJdlVBRVJqUkh3Sk1Tb1g5b2J6cG5PbFhyQWNVOGZKbDVwUwpEZ01mcFNCbXRucVZJQzM5VVJJdS92cXRBd1lsbXZTaHAzd244TER2bW5CQUNkWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key:  LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRRGpGZDVhMjZPaFZrU04KRnY5MXhpVVVyWWNPaTEyN05zSklicUozT0JyL0dkOVFMVERFQUIvTkF4MGgxcnpZclRrdy85SXc2b09la1U0MgpuRmJ1cm1zOGhkcWFNM3BadGYzNXN0WWcvUjFRV1RiVzc3ZjdLOUZ0azZxTldHWEx3NU4vSmNzOE1xa3NhY1MwCnJRdTIvMVdnSGFHeUkxbzhhOTVKNmJmQktNek9vRnZVR0RKUW5pM3hCaUFLVCs0RXVUandyWXYrSE1ra1JkWWcKaEJwZXBmdzRNVXNyNFBXeWltTk5RMzhPOUwvSStwK3VjRGRFLzZZaGdvVHRtZVREM2xFRjdEeEdBVEwyMEdqYQo2Z1MxNDIwUE82MStJLzZiWkQyL2hoZTVqcXBZTldFUzJlcWdiRGg1VmFLVURpdlo4VzFiUVdoVk1uSVpFbWdTCkdOWVgrL1RTcWs2MVVOWTVYTHhmMi9UWVBmWFRTV1ZhdXFyWkxsTmI3czk0S2RneEMyTEkzcHhCK3J3cmh2K3QKTU4rdnE5MEZiRVg4SExiZ2psc0lQalVUUS9yT2hmK253YkFXTkkyaFFvRGxiSzhFMktZQXNwd25oWm44dkI1VQptejZrdVVhT1ZrdlNyZys1STJsakZlNXEwMTB2V3BKUmY2MDZGRWpVVmpLMGJVZzU4QXJSSldoMmNoQWpxVU03ClR6b1IxU0ZJSS9qaG9LK2t4aXdvRE1LUGtDaGVSZCszZjlaaE9jck9uZkpmWlZVemVpYWkxd0xPV1IxVjFTQkoKczNhdFpLR09JRlZjczd6QjJVcDBVbnRSYnRPU0lGRC9FY2pLUTc4U3ZHdUNRa29ZNEl1M29HSHVBTWRUMU1scgpPY2wvOEtIQ1c1ZXhXZXRDK0wzTy9uWUp6NGxVZXdJREFRQUJBb0lDQVFDL2RIS1J1OWhMY0FZL3hnSC9jOTFUCmY3SDhhemZOWGErVGplTmdER2VHYUhQRWp6VXNLc2FrL0ZrVmJJeXZTZXlNQ1VOWGhvRU5zWWgxdG4zOG9nVTcKYzhjSWR4cFNoSVBxZ0FMVXNWS0RxWlA0eHdjZ3RxTE5kZEEzZHkzc0M2cFJhclhjdlFHd3RrUG42SFdXQmRSVgpPR1paWUVEMTdDUHZ3U0x4c2NwcTh2dzQ1MldVWHFoeEt5N2NRdU4wREEyYnJWWDRHcURpK2hZOE4rUmJwQ252CjNtOTRRU1FsTVZQamttS1BZMzVHbmpiK3hSRjBGTzRtRm5xb01EV1ZoZHhkMS94Qk1VV2NuYjJwdzkvUTBqdmkKdWZmZC84N3JpQ29mVFppM0V6Yy9RMUhpcU9PTitXL3JyRzF6MGpiYWV4Z3Q5Z2xXdXo5RE1DZWFDbUtHdWlCLwozZ1UyU0xhdlR2TDlFdzFWMDNJUjhaM2ZySFliZEVKTGl3K25KL1hmM00rS21ESjZtajA0Q0hjbGpBVGI1UzFXCkZLeUJoMWYzdVJoeDF1M29IeCtEUWh0cVFsc1FLUUQyKzBnK3RzcEl0VGtJWmI5blp6bm5abVNPZjRLMG9TdWUKWEVKbVZRZjNSSEpxanJWZGpzdHM0NVZxdnJlQ2FDci8yLytHb0tTaUNDdTJGMmhsNTVQSkNlTHFzWk5FdGlFSwpmVW1od2xDL05QOXFvMG9pczRIbTBzV3FzOWtPODRHSmJaZ24zL0h3azFzenhJSEdZMDBsZFdGcWNvNFVrYWhnClo1UWpRd0tnYjhlNDNRYkFKR2htVjFzV0NqZjYvY2llb3l5VHRxN1o4ZXlZZDZLL2ljZ3pRWUxqTnRuNFhWcWgKaXRkaU9jL2JYYVl3cFZYbllZSVVzUUtDQVFFQTlQaFY2QkpyVmJtR3FnUy9WT0NZVjQ1ckNIZWRDczlDOXNoZwo5RlRvSWNaUzBZclhxNUJrQ0JkdE5hUStCa3pBdmlnQnZud1RvdUNoeHJjSlFrSXpWcTAxSUNyTHY5emROTGduCm1LU1I1TzRGRDRxdjZrYUtGUkVuQVBiTk1sOEJYOE1rUHlEU1EyZVhwbmQwRmZJb0FENmtBaXpianNuN1gwaG4KaWE0L2E0b2wzMHdoTlZhb2g5SE1rcEk4UGxJNGE3bFphOVVZVGh2N0wrZWRTbHNiUStueUtKQjhLeHpUTG5JZgpqbkFRb1FybUlvclpySlIybXFma1J4Mm1oRzdOa0FHTzhiWHRicldSYytLK1NuK1JFaWU5R0dxL2N5TTdXWlgxCkt6U2RrWWVKelYrZmFwbnNNVUVtQitKMGZURzZ3VlV2WGl1V1RlcWp2QUJoa3ZhNHh3S0NBUUVBN1U5aWJpNWcKV21wcTcybkpteHVHWDdGQTZlUS8xL05Vd2d2RTVmZFdOTjJVQXB4VTl6VDEvdGR1ZVdqVXBjN2JOZ3FzNUswKwpXbGs5dWNzN1U1SnZ3V2J4Y1BmcG5Rbzl3L2p2Z0FjbkRkZHhuS05xVTBHRHdicTJsZ1dXVkhMSFovZnBTVVlLCmJZcTZORU0vVk5NbjA1ZnVoVDgwRXZVaHRhZlNMeGp4T0VLOXZJVzlnczZXTlZITGRBYkxST3g0UXJSaWJaSUQKcS8wV25zMzIzdEtZL0l2WFNyOEFaa3BLZitkODFzamoyWXQrSStnOW1FQzlWcy9WY1pKT1Q1V0RHY00zd2xCLwoxMGltUHZWQU9NSUFPUFNnd01US1pZdzV4czE1NEJPWkEwZkdXdzk0RFFUU3FuWjhJdElkcE5BbmRBcVNTVnFFCm82Q0VuZURiQytQYXJRS0NBUUFxOWFYekZjL1c3N3NxODd3dUFWa1YrYmJSZkZDQkJjbmpoMDVoYXNadXJkMzIKTzFnSkVVQkpudm9hN3h1bGRTNVQ2cVlycG95M0FwZThSbnNNTUpuYU9IUFptVWV6OU9LaURTMThlbGZQZ3VKRwpVSGI3S2JXcmJoK2Q3cW9iakVlc2FJZGh2cnJBOFZqSjY2Ymk5bDJIZFhURG9PUThEVFhWQnRpSmI1SlZwSnR4CnBtTW9mSEwvcG80dW9oQ0lpVmkxbzRLSUE0M0luT1dYQ0JJd2FQdkdGQy9RWjA0dkxWWG5qa0gwYzdpbTFVZDQKaFVzWkZjd2E0UmlLVkN2UWk3SG04QzhHT25aUjlPdDJIQ3hzMmlReHYrQk1lT1BzS0NDUFhGbnJZc1hETUxhOAoybWtWZzdyRkJIekw0eTIwaXRVS2RJcmpBOWZQQURnSWp6U05WbEVmQW9JQkFEM05xdWpmRXlENURoaUVDSWxvCnhib3VRNldtV0NvNXFSMVFTMXRJNng2aGhtYVhxRmtwWmRlVTY2U2E5S2FxRk5VaU9wempzWlYrSUdFKzJKaVAKVHFPajE4V0FDMHRtMjJjcWNkVjZCMlhIY2tORkcrL0s1REdVR3ZFL1MwTjdFUXUydVA3b1N0YjBoa0lPTVhRNQorZWxWYkQwdmxMUkxPeGhBT0xFalljOHhNcERpazlSNVVRMVozQTYvcGppeERURHlJYUEvb3Mwc0FMUWpGK1E0CkhMZkpBNnpueVliYVdrU3RXUW5uRDlBY1VDR3gzampFdzRyVVhkWlNNQ3J4MlU3Z1ZLazZwZEMvanV4ZW12Y3QKTHptbUhDZVlHTTRSa3dwL2dQb21vSGNHUGxhQTFOY3ZKbDVXdFVXc1N5UWRRZWtxeDZacStKaFV1YlVVVm5mbQpRNUVDZ2dFQVpBZStWenMrRVVNeW96MVdQQzRBYlpjTzdRZTd5VHlmTkFYZHZVbVJtb2x6ZmFNN3VIUXN3L0ZPClZhYWZJcTZraXArb21VTE16cnIzaURrWjJ0Rjk1Nk9JdkR2Uk9DVXpIb2MxSVdMQnVod2UyMWI3ZDZyUnpoeHkKTUt4MmNCSDJlL09Za012K0VLRnVGYmw5WHFnT0JNNGJrY2ZBR0JuUVZZTmVZWGlCQUs0WDNRM0ZsRW9HeFhEWApOU3B1SmhRbC9OQUJLS0VBb2hZVXBVbzUwZTBGb1IvMTQ5WFRSbmRpU0prRXNqZSt2TGtMak0vYUtxclo1U1UvCmtha1dCdFVqLzVkclg5d05CTWpsYzQyWDBTNThKNDc1Vkd3a2tmcGo4bFBNbnM1dHJua1Z1dEVlWE5CT1Q5N2cKNGV4QnRoYjNTRUt0UGx5T3hML3VNdG04TmkwcmZBPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:edge
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
 
